### PR TITLE
Update esp32.md

### PR DESCRIPTION
**Pull request by FinkeFlo**
Added screenshots of reading the flash

### CODE REVIEW

**Comment by SciLor** [comment]
Please add the images to the [repository](https://github.com/toniebox-reverse-engineering/toniebox-reverse-engineering.github.io/tree/master/static/img) with a good name. Please also use a descriptive alt-image description for it instead of just "screenshit"

**Comment by SciLor** [comment]
Thank you, but please also use the images in the .md (check the relative path in other wiki files)

**Comment by SciLor** [comment]
https://github.com/toniebox-reverse-engineering/toniebox-reverse-engineering.github.io/blob/master/content/docs/custom-firmware/cc3200/hackieboxng-bl/bootloader.md?plain=1

Please remove /static/

**Comment by FinkeFlo** [comment]
But then i don't see the image anymore
image

**Comment by SciLor** [comment]
You don't see the images in the preview, that's true. But only this way, the images will be visible on the website later on.

**Comment by SciLor** [comment]
Thank you for this PR

**Pull request merged**
