### PR TITLE
Update _index.md

### PR DESCRIPTION
**Pull request by andreasloe**
link to releases

### CODE REVIEW

**Comment by SciLor** [comment]
Hey andreas,
I don't understand what this link should do?

https://toniebox-reverse-engineering.github.io/docs/tools/teddybench/

**Comment by andreasloe** [comment]
Oh, I was browsing the wiki and since I am new to github it took me a while to find the release directory. I just wanted to change that in the wiki (if I am correct it does not contain information at the moment). 

If I made a mistake then disregard my "patch".

**Comment by andreasloe** [comment]
BTW thanks for the great work.

**Comment by SciLor** [comment]
Thank you.
This PR only adds metadata for Hugo, that won't be used for Hugo. So this PR just removes the "Test" text.

The website is missing some details about teddyBench and also a link to its repo and releases.

**Pull request closed without merging**
