### PR TITLE
Adds detailed steps for Synology NAS setup

### PR DESCRIPTION
**Pull request by HappyZ**

### CODE REVIEW

**Comment by henryk86** [comment]
Please move this to a separate page as this does not belong to the supported hardware directly.

**Comment by HappyZ** [comment]
Makes sense, how do you want the doc to be structured? 

(a side question: I don't find user manual for TeddyCloud web interface, is that planned to be add (after Setup section)?

**Comment by SciLor** [comment]
Please remove the full docker compose example, as this may be outdated very fast.
In addition, the macvlan is a general thing, not exclusively to the NAS. So it makes sense to split this up into how to macvlan and the hint, that the NAS blocks the needed ports

**Comment by henryk86** [comment]
> a side question: I don't find user manual for TeddyCloud web interface, is that planned to be add (after Setup section

Some faq is in the web gui itself, some help buttons also. But it could be extended. As now the gui is not finished, we wait till we put a lot of effort in it and try to make everything obvious and easy to use. 
antd provides some guided help which could be added later also.

for now feel free to use the forum to post some kind of a guide. (It’s easier to edit there and if the gui is in a stable version, it can be transferred to the wiki)

**Comment by HappyZ** [comment]
gotcha, it seems you have in mind already how the user guide would look like so I will not disrupt it. I can drop this one and help contribute adding more examples in other formats.

**Pull request closed without merging**
